name: run-int-tests
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    services:
      redis:
        image: 'bitnami/redis:latest'
        env:
          ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: "16"
      - run: npm install
      - run: npm run test:int
